### ISSUE TITLE
64-bit support?

### ISSUE THREAD

**Issue by bcpi** [benbahrenburg/Ti.Light#1]
Hi,

Thanks for making this module. We've been using it on our app and it works really well. We have version 0.1 at the moment from the "dist" folder.

Is this version 64-bit ready? We plan on making our app 64-bit ready before the february 1, 2015 deadline.

Thanks!

**Comment by bcpi** [comment]
Hi. What would be required to make this module 64bit compatible? I'm not great with Xcode projects, but if it's just changing a few settings, then compiling I'll give it a try. Thanks!

**Comment by ikruglik** [comment]
Hello, It appears the new release has the same v0.1 iOS module. I've tried to re-compile it to be 64-bit compatible, without luck though. Do you have any ETA to upgrade the iOS module version? Thank you.

**Comment by ikruglik** [comment]
Never mind, got is sorted out myself.

PS
Thank you for fixing Android bug that was not releasing camera resources properly.

**Comment by benbahrenburg** [comment]
iOS version has been updated and pushed to Github
