### ISSUE TITLE
Don't work on NEXUS5 

### ISSUE THREAD

**Issue by AppWerft** [benbahrenburg/Ti.Light#2]
Hi Ben,

you module doesn't work on NEXUS5 API20. 

```
var torch = require('ti.light');
torch.toggle();
//[INFO] :   info: (KrollRuntimeThread) [584,741018] torch is turn on!
//[INFO] :   TilightModule: (KrollRuntimeThread) [783,741801] torch is turn off!
```

Same issue with the module of viezel. 

```
var NappFlashLight = require('dk.napp.flashlight');
if (NappFlashLight.isFlashLightSupported()) {
    Ti.API.info("hardware support for flashlight");
    NappFlashLight.turnFlashLightOn();
    setInterval(function() {
        NappFlashLight.toggleFlashLight();
    }, 1000);
} else {
    Ti.API.error("No hardware support for flashlight");
}
```

**Comment by manumaticx** [comment]
I have the same issue. No light on Nexus 5. I've just build the module from source and can confirm that 261debfa5c611b86f07cebd7e74f8cc06d6d2c24 seems to fix it as turning on the flashlight works. But you can't turn it off anymore.

**Comment by benbahrenburg** [comment]
@manumaticx does this solve the "unable to turn off" issue?

**Comment by manumaticx** [comment]
@benbahrenburg Yes. Turning off works. I think the `camera.release();` in your yesterdays commit did the trick. But it lights up again for a millisecond before turning off.

**Comment by AppWerft** [comment]
Hi,
maybe a stupide question,but what is with these events:

```
@Override
public void onStop(Activity activity) {
super.onStop(activity);
torch.turnOff();
}
@Override
public void onPause(Activity activity) {
super.onPause(activity);
torch.turnOff();
}
```

**Comment by manumaticx** [comment]
@AppWerft This would turn off the light when you close the app / activity. This may not be intended. But you can do the same thing from within the titanium app since these callbacks are exposed to the [Activity](http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.Android.Activity)

**Comment by AppWerft** [comment]
@Manu Currently I cannot build, because the folder 'lib' is missing in downloaded ZIP

**Comment by manumaticx** [comment]
@AppWerft you can create this folder and run `ant` to build the module. Or wait if @benbahrenburg adds a new dist!?

**Comment by benbahrenburg** [comment]
will post a new version later today

**Comment by AppWerft** [comment]
Hint from Mani: https://github.com/Gark/flashlight/blob/master/app/src/main/java/gark/flashlight/controls/CFlashLight.java is enhanced version with switch of devices.

**Comment by benbahrenburg** [comment]
@AppWerft seems alittle overkill for a module demonstrating how to create native modules. If you'd like to contribute in a cross-platform way, I'm happy to take a PR
