### ISSUE TITLE
iOS 0.2 don't works

### ISSUE THREAD

**Issue by Astrovic** [benbahrenburg/Ti.Light#7]
Hi Ben,
I tried to download the latest version, but Titanium always sees only the 0.1. I also tried to build the module, but Titanium continues to see only the version 0.1. If I delete the version 0.1, Titanium does not see the module.  I find it strange...

**Comment by ikruglik** [comment]
I was able to compile my application with the v0.2 iOS module. Try to clean your project as well as the modules folder and re-install the 0.2 version, check tiapp.XML config. What is the Titanium and XCode version, BTW?

**Comment by ikruglik** [comment]
I was able to compile my application with the v0.2 iOS module. Try to clean your project as well as the modules folder and re-install the 0.2 version, check tiapp.XML config. What is the Titanium and XCode version, BTW?

**Comment by Astrovic** [comment]
Thanks for your response. I use Titanium 3.5.0 GA and xCode 6.1.1. I've done a project clean. I also removed the module from Titanium Modules and from the project modules of the app. I tried to insert the module only into the app project. But in all cases, I still see only the version 0.1 :/
Obviously I've done other builds, to make them compatible with x64.

**Comment by Astrovic** [comment]
Ok, I'm stupid... I had forgotten to set the Titanium SDK project to 3.5.0 GA. 
It works perfectly. Thanks a lot for the support and congratulations Ben for the module!
