### ISSUE TITLE
java.lang.UnsatisfiedLinkError has text relocations on Android 6.0

### ISSUE THREAD

**Issue by joe-f** [benbahrenburg/Ti.Light#9]
Get the following error as soon as launching an app using this module on Android 6.0
`java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.crowdglow.braeheadclan-1/lib/arm/libti.light.so: has text relocations
    at java.lang.Runtime.loadLibrary(Runtime.java:372)
    at java.lang.System.loadLibrary(System.java:1076)
    at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
    at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
    at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)`

Apparently the module just needs re-compiled with the latest NDK/SDK according to this link: https://github.com/appcelerator-modules/ti.compression/issues/6

Any chance a new distribution build could be produced?

Thanks!

**Comment by benbahrenburg** [comment]
updated

**Comment by joe-f** [comment]
Thanks for the quick turn around on this!

However I'm now getting the following error:
`2-03 20:46:26.367  3961  3961 E TiApplication: (main) [13,115] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to create application com.crowdglow.braeheadclan.BraeheadClanApplication: java.lang.RuntimeException: Fail to connect to camera service; Titanium 5.1.1,2015/11/24 11:07,e46100b
02-03 20:46:26.367  3961  3961 E TiApplication: java.lang.RuntimeException: Unable to create application com.crowdglow.braeheadclan.BraeheadClanApplication: java.lang.RuntimeException: Fail to connect to camera service
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.os.Looper.loop(Looper.java:148)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.app.ActivityThread.main(ActivityThread.java:5417)
02-03 20:46:26.367  3961  3961 E TiApplication:     at java.lang.reflect.Method.invoke(Native Method)
02-03 20:46:26.367  3961  3961 E TiApplication:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-03 20:46:26.367  3961  3961 E TiApplication:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-03 20:46:26.367  3961  3961 E TiApplication: Caused by: java.lang.RuntimeException: Fail to connect to camera service
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.hardware.Camera.<init>(Camera.java:495)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.hardware.Camera.open(Camera.java:356)
02-03 20:46:26.367  3961  3961 E TiApplication:     at ti.light.TilightModule.onAppCreate(TilightModule.java:48)
02-03 20:46:26.367  3961  3961 E TiApplication:     at com.crowdglow.braeheadclan.BraeheadClanApplication.onCreate(BraeheadClanApplication.java:104)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
02-03 20:46:26.367  3961  3961 E TiApplication:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
02-03 20:46:26.367  3961  3961 E TiApplication:     ... 8 more
`
Any ideas?

**Comment by benbahrenburg** [comment]
Could be a permissions issue. You might want to explore granting the camera permission.  Best to test by actually creating the camera dialog.  If that doesn't work, would recommend downloading the module and placing log statements where needed.
